spring:
    h2:
        console:
            enabled: true
            path: /h2-console
            settings.trace: false
            settings.web-allow-others: false
    datasource:
        url: jdbc:h2:mem:mydb
        username: sa
        password: password
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                globally_quoted_identifiers: true

server:
    port: 8095
#    servlet :
#        context-path : /api/v1/campaign

#spring:
#    sql :
#        init :
#            mode : always
#    datasource:
#        driverClassName: org.postgresql.Driver
#        username: postgres
#        password: rootpassword
#        url: jdbc:postgresql://localhost:5432/postgres?currentSchema=campaign
##        driver-class-name: com.mysql.cj.jdbc.Driver
##        url: jdbc:mysql://localhost:3306/login_ms
##        username: root
##        password: password
#    jackson :
#        serialization :
#            FAIL_ON_EMPTY_BEANS : false
#    jpa:
#        hibernate:
#            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
#            generate-ddl: true
#            ddl-auto: update
#        properties:
#            hibernate:
##                dialect: org.hibernate.dialect.MySQL8Dialect
#                dialect: org.hibernate.dialect.PostgreSQLDialect
#                storage_engine: innodb
#                temp:
#                    use_jdbc_metadata_defaults: false
#            show-sql: true
#            format-sql: true
#        defer-datasource-initialization: true
#        main:
#            allow-bean-definition-overriding: true
#    mvc :
#        pathmatch :
#            matching-strategy : ANT_PATH_MATCHER
#
#logging:
#    level:
#        root: INFO
#    file: /log/file.log
#    pattern:
#        console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestUUID}] [%thread] %-5level  %logger{1}:%L - %msg%n"
#        file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%X{requestUUID}] [%thread] %-5level  %logger{1}:%L - %msg%n"
